.TH STARTPY 1 "2026-09-02" "startxpy 0.6.2" "User Commands"
.SH NAME
startxpy \- IDE-like launcher/windowing framework for Python/Tkinter projects
.SH SYNOPSIS
.B startxpy
[\fIOPTIONS\fR]
.SH DESCRIPTION
\fBstartxpy\fR is a small framework to launch and manage Tkinter-based IDE-like windows,
with mixins for menubar, statusbar, taskbar, dev-toolbar, etc.

It is primarily intended as a Python library for building custom IDE-style applications
rather than as a standalone command-line tool. The \fBstartxpy\fR command is provided
as a convenience wrapper to launch example or default configurations.
.SH OPTIONS
No options are currently implemented.
.SH EXAMPLES
.IP
.nf
startxpy
.fi
.SH SEE ALSO
Python documentation, Tkinter documentation.
.SH AUTHOR
Lev <levikabd@yandex.ru>
.SH COPYRIGHT
Copyright (C) 2026 Lev. Licensed under the terms of the project license.
